### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by vcharpenay** [thingweb/node-red-contrib-web-of-things#1]
After using the WoT nodes for our [summer school on AI for the industry](https://ai4industry.sciencesconf.org/), there are a couple of fixes/features we'd like to suggest:
 - when loading several TDs to a flow, it is not easy to distinguish them in the drop-down list when configuring a node. All TDs have the same label (something like `thing-description`)
   - feat: use TDs' `title` instead
-  if an action has no output, no message is sent downstream after an `invokeAction` node.
   - fix: bump `node-wot` to REC version
   - fix: send emtpy message (if first fix doesn't suffice)

**Comment by fatadel** [comment]
Dear @vcharpenay,

Thank you very much for your feedback!
We have resolved your issue and pushed the new version to npm as well.

Feel free to give a new feedback.

Best regards,
Adel
