### ISSUE TITLE
Support for WoT Discovery?

### ISSUE THREAD

**Issue by JKRhb** [thingweb/node-red-contrib-web-of-things#12]
First of all, thanks for providing this very cool package!

I just wanted to ask if there are any plans to support the existing discovery (or rather: introduction) mechanisms specified in the [Web of Things (WoT) Discovery Working Draft](https://www.w3.org/TR/wot-discovery/). 

I think it could open many possibilities if you could retrieve existing Thing Descriptions in a network and interact with the so found devices, maybe even on the basis of a set of conditions. One example that came to my mind would be to turn on all available lights by first finding devices which are of `@type` `saref:LightSwitch` and then invoking those `actionAffordances` which are of `@type` `saref:OnCommand`.

**Comment by danielpeintner** [comment]
> I just wanted to ask if there are any plans to support the existing discovery (or rather: introduction) mechanisms specified in the [Web of Things (WoT) Discovery Working Draft](https://www.w3.org/TR/wot-discovery/).

Hi, we surely plan for support WoT discovery. Having said that, there is no timeline yet.
The API is also in flight at the moment and we will definitely wait a bit till this is settled (see https://github.com/w3c/wot-scripting-api/issues?q=is%3Aissue+is%3Aopen+label%3Adiscovery)...
