### ISSUE TITLE
No possibility to provide username and password

### ISSUE THREAD

**Issue by JKRhb** [thingweb/node-red-contrib-web-of-things#16]
When processing a TD (for example [this TD](https://github.com/w3c/wot-testing/blob/main/events/2021.03.Online/TDs/Oracle/oracle-Festo_Shared.td.jsonld) from the WoT plugfest) that uses the `basic` security scheme there is – if I am not mistaken – currently no possibility to provide the username and password that are needed for accessing the thing's resources.

**Comment by egekorkan** [comment]
Done as well, closing.
