### ISSUE TITLE
Server-side node development

### ISSUE THREAD

**Issue by hidetak** [thingweb/node-red-contrib-web-of-things#25]
Dear Contributors,

Thank you for providing a node for easy use of WoT from Node-RED.

Currently, there seemed to be no server-side WoT node, so I developed one.
https://github.com/hidetak/node-red-contrib-web-of-things

I have also created a demo movie showing how to use this node, and would be very happy to receive your feedback.
https://drive.google.com/file/d/1UOpbvwMMoi6znIsVR8AoOX2x8rP3ohSc/view

Currently, it can only handle simple use cases, but I would like to know if the basic concepts of the node specifications are the same as yours.

Also, as mentioned at the end of the README, there seemed to be some features that were not available in CoAP and MQTT Binding. It is possible that I am using them incorrectly, but I would be grateful for your advice if you have knowledge about this as well (WebSocket is available as an option, but I have not been able to confirm its operation).

If you would like, I would be happy to submit a pull request to this repository.

Thank you in advance.

**Comment by egekorkan** [comment]
@hidetak , first of all thank you very much for doing the work! Some meta comments:
- Your contributions are in TypeScript but the initial codebase is JS (I prefer yours).
- You have done a big update to node-wot versions (which is nice). Have you tested the client side?
- I will bring this up in next week's call. We have been thinking about bringing this to Eclipse repository but did not have the bandwidth so far. If you are interested, please join our next week's call :) The information is available at https://github.com/eclipse-thingweb/thingweb/wiki/Meetings
- Also please note that if you make a contribution to this repository, it is not protected under Eclipse Contributors License. This organization is the precursor to Eclipse Thingweb and is not active. You can of course make a PR and we will evaluate this but this can be very important to some people.

Pinging @danielpeintner , @relu91, @JKRhb

**Comment by hidetak** [comment]
@egekorkan 

Thank you for your comment.

> You have done a big update to node-wot versions (which is nice). Have you tested the client side?

The client-side program has been changed to match the new implementation of node-wot.  I have performed the operational checks shown in the movie, but have not been able to add any additional tests.

> I will bring this up in next week's call. We have been thinking about bringing this to Eclipse repository but did not have the bandwidth so far. If you are interested, please join our next week's call :) The information is available at https://github.com/eclipse-thingweb/thingweb/wiki/Meetings

Thank you very much.
I would like to participate if it is convenient, but I may not be able to join the discussion since my English is not good enough.

> Also please note that if you make a contribution to this repository, it is not protected under Eclipse Contributors License. This organization is the precursor to Eclipse Thingweb and is not active. You can of course make a PR and we will evaluate this but this can be very important to some people.

Will you be adopting EPL-2.0 as well as node-wot?
I have no problem changing to EPL-2.0.
I will create a PR to this repository.

**Comment by Citrullin** [comment]
@hidetak Since you are already touching this, maybe you want to take parts from @JKRhb implementation.
He did some interesting things, especially in the discovery part. It's worth checking out.
https://github.com/namib-project/node-red-contrib-wot-discovery

**Comment by hidetak** [comment]
@Citrullin 

Thanks for sharing the information.

I understood that the node you mentioned is a node to retrieve the ThingDescription registered on the server.
I thought that if the WoT server node could have the mechanism to register the ThingDescription to the above server, it would be able to work well with the client.
I am not familiar with the Discovery specification, but if there is an implementation of a server that can be used as a registration destination for ThingDescription, I would consider adding the functionality.

My apologies if this is not the intended response to your comment.

**Comment by Citrullin** [comment]
> I understood that the node you mentioned is a node to retrieve the ThingDescription registered on the server.

The difference in the retrieval is that the other implementation pulls the WoT TD by itself whenever it is triggered.
You don't have to do it manually as you have shown it in your video. It's not as much as registered and more of the servient which hosts its own TD or of sensors/actuators behind it.
Getting the TD from the TDD (Thing Description Directory) would be another interesting use-case, of course.
You can find the current spec here btw: https://www.w3.org/TR/wot-discovery/
The best maintained TDD at the moment is probably Zion: https://github.com/vaimee/zion

> My apologies if this is not the intended response to your comment.

Don't worry, everything is fine. Just wanted to point you into the direction. :)

**Comment by hidetak** [comment]
@Citrullin 

You are referring to a system in which TDs are entered and processed each time in the wot-scripting node.
I thought it was a good mechanism to work together in situations where the TD changes dynamically, without having to change the client implementation.

Also, thank you for the introduction to the Discovery specification and implementation.
I will take a look at it.

Thank you for the introduction!
If you have any interesting use cases for WoT, I would be glad to hear from you again.

**Comment by relu91** [comment]
It's great to see some advancement here, I'm definitely in favor of moving this under Eclipse but let's discuss it tomorrow. I'm also in favor of adding Discovery as Jan experimented with the Namib project.

**Comment by egekorkan** [comment]
The PR #26 has addressed this and the move is finished
